### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by TheDeathConqueror** [Leanty/tree-gateway#110]
I'm trying to install `tree-gateway` using npm and yarn. But both ways it is failing. I'm not sure  with the exact reason. But it seems some issue with installation of deep dependencies like `node-gyp`, `node-pre-gyp`. 

Though I'm not sure about all the dependencies but can I request to move to the packages which are based on less dependencies or good performance? E.g. if we use `bcryptjs` instead of `bcrypt`, `fast-xml-parser` instead of `xml2js`,  etc.

**Comment by thiagobustamante** [comment]
Hi, thanks for reporting. Can you post here the complete error stack and the platform you are using (windows / linux / mac version, node and npm versions)?

I think that we should change bcrypt to bcryptjs, once it is used only to authenticate admin users on gateway rest API . It is not used during the request pipeline of proxied APIs. So it is not a big volume and I think that reduce the dependencies is more important than performance in this scenario. But the same is not true about xml parsing.... We use xml parsers in interceptors that allow transform the request or response bodies. In that scenario I think we need to have the best performance possible.

**Comment by TheDeathConqueror** [comment]
Thanks for your quick response.

I believe this is not the bug related to this library so you may want to change the label from `bug` to `question`. 

When I run `$sudo yarn global add tree-gateway`, it runs for few minutes then error out with following;

```
$ sudo yarn global add tree-gateway
yarn global v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/2] ⠄ waiting...
[2/2] ⠄ gc-stats: install got an error, rolling back install
[-/2] ⡀ waiting...
[-/2] ⡀ waiting...
error /usr/local/share/.config/yarn/global/node_modules/gc-stats: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /usr/local/share/.config/yarn/global/node_modules/gc-stats
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.36
node-pre-gyp info using node@9.4.0 | linux | x64
node-pre-gyp info check checked for "/usr/local/share/.config/yarn/global/node_modules/gc-stats/build/gcstats/v1.1.0/Release/node-v59-linux-x64/gcstats.node" (not found)
node-pre-gyp http GET https://node-binaries.s3.amazonaws.com/gcstats/v1.1.0/Release/node-v59-linux-x64.tar.gz
node-pre-gyp http 403 https://node-binaries.s3.amazonaws.com/gcstats/v1.1.0/Release/node-v59-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(403): https://node-binaries.s3.amazonaws.com/gcstats/v1.1.0/Release/node-v59-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for gc-stats@1.1.0 and node@9.4.0 (node-v59 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 403 status code downloading tarball https://node-binaries.s3.amazonaws.com/gcstats/v1.1.0/Release/node-v59-linux-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.4.0 | linux | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.4.0 | linux | x64
gyp http GET https://nodejs.org/download/release/v9.4.0/node-v9.4.0-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: connect ETIMEDOUT 104.20.23.46:443
gyp ERR! stack     at Object._errnoException (util.js:1003:13)
gyp ERR! stack     at _exceptionWithHostPort (util.js:1024:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1194:14)
gyp ERR! System Linux 4.13.0-32-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/share/.config/yarn/global/node_modules/gc-stats/build/gcstats/v1.1.0/Release/node-v59-linux-x64/gcstats.node" "--module_name=gcstats" "--module_path=/usr/local/share/.config/yarn/global/node_modules/gc-stats/build/gcstats/v1.1.0/Release/node-v59-linux-x64"
gyp ERR! cwd /usr/local/share/.config/yarn/global/node_modules/gc-stats
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/share/.config/yarn/global/node_modules/gc-stats/build/gcstats/v1.1.0/Release/node-v59-linux-x64/gcstats.node --module_name=gcstats --module_path=/usr/local/share/.config/yarn/global/node_modules/gc-stats/build/gcstats/v1.1.0/Release/node-v59-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/gc-stats/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Linux 4.13.0-32-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/share/.config/yarn/global/node_modules/gc-stats/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/share/.config/yarn/global/node_modules/gc-stats
node-pre-gyp ERR! node -v v9.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp

```

Since changing to any library may require extra burden so it's up to you, I just suggested as I found your package very helpful, almost complete, solving most of the concerns of API gateway, and growing.

**Comment by thiagobustamante** [comment]
@TheDeathConqueror 

I published a new version that change this dependency. As I said before, it is not really required and will not impact the gateway performance. It is used in a very low usage scenario... And I agree that it can simplify our dependency tree.

Please, try the 2.0.1 version and let us know if your issue disappear.

**Comment by TheDeathConqueror** [comment]
Unfortunately it faild.

```bash
/usr/local/bin/treeGateway -> /usr/local/lib/node_modules/tree-gateway/dist/index.js
/usr/local/bin/treeGatewayConfig -> /usr/local/lib/node_modules/tree-gateway/dist/admin/config/cli.js

> gc-stats@1.1.0 install /usr/local/lib/node_modules/tree-gateway/node_modules/gc-stats
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://node-binaries.s3.amazonaws.com/gcstats/v1.1.0/Release/node-v59-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for gc-stats@1.1.0 and node@9.4.0 (node-v59 ABI) (falling back to source compile with node-gyp) 
gypnode-pre-gyp ERR! Tried to download(undefined): https://node-binaries.s3.amazonaws.com/gcstats/v1.1.0/Release/node-v59-linux-x64.tar.gz 
node-pre-gyp  ERR! Pre-built binaries not found for gc-stats@1.1.0 and node@9.4.0 (node-v59 ABI) (falling back to source compile with node-gyp) 
WARN install got an error, rolling back install
:
```

**Comment by thiagobustamante** [comment]
Hum... gc-stats needs node-pre-gyp. It is used by garbage collector monitor.

Your build is failing because node-pre-gyp could not be installed. One
package could not be downloaded... I never had this issue. Are you behind
some proxy?

Em 13 de fev de 2018 11:15 AM, "TheDeathConqueror" <notifications@github.com>
escreveu:

**Comment by thiagobustamante** [comment]
I Saw that you are using node 9.4. Can you try to test with node 8.x?

Em 13 de fev de 2018 3:34 PM, "Thiago da Rosa Bustamante" <
trbustamante@gmail.com> escreveu:

Hum... gc-stats needs node-pre-gyp. It is used by garbage collector monitor.

Your build is failing because node-pre-gyp could not be installed. One
package could not be downloaded... I never had this issue. Are you behind
some proxy?

Em 13 de fev de 2018 11:15 AM, "TheDeathConqueror" <notifications@github.com>
escreveu:

**Comment by thiagobustamante** [comment]
@TheDeathConqueror ,

Can you try to run manually:

```sh
npm i -g node-pre-gyp
```

And then reinstall the gateway?

**Comment by TheDeathConqueror** [comment]
wow. this trick worked. Thanks a lot. You made my day
