### ISSUE TITLE
Swagger Client dependence base64-js not found 

### ISSUE THREAD

**Issue by geldoronie** [Leanty/tree-gateway#145]
```
tree-gateway_1  | internal/modules/cjs/loader.js:550
tree-gateway_1  |     throw err;
tree-gateway_1  |     ^
tree-gateway_1  | 
tree-gateway_1  | Error: Cannot find module 'base64-js'
tree-gateway_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
tree-gateway_1  |     at Function.Module._load (internal/modules/cjs/loader.js:475:25)
tree-gateway_1  |     at Module.require (internal/modules/cjs/loader.js:598:17)
tree-gateway_1  |     at require (internal/modules/cjs/helpers.js:11:18)
tree-gateway_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/tree-gateway/node_modules/swagger-client/dist/index.js:7:11309)
tree-gateway_1  |     at t (/usr/local/lib/node_modules/tree-gateway/node_modules/swagger-client/dist/index.js:1:177)
tree-gateway_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/tree-gateway/node_modules/swagger-client/dist/index.js:7:7)
tree-gateway_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/tree-gateway/node_modules/swagger-client/dist/index.js:7:11111)
tree-gateway_1  |     at t (/usr/local/lib/node_modules/tree-gateway/node_modules/swagger-client/dist/index.js:1:177)
tree-gateway_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/tree-gateway/node_modules/swagger-client/dist/index.js:1:48717)
tree-gateway_1  |     at t (/usr/local/lib/node_modules/tree-gateway/node_modules/swagger-client/dist/index.js:1:177)
tree-gateway_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/tree-gateway/node_modules/swagger-client/dist/index.js:1:40420)
tree-gateway_1  |     at t (/usr/local/lib/node_modules/tree-gateway/node_modules/swagger-client/dist/index.js:1:177)
tree-gateway_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/tree-gateway/node_modules/swagger-client/dist/index.js:1:16408)
tree-gateway_1  |     at t (/usr/local/lib/node_modules/tree-gateway/node_modules/swagger-client/dist/index.js:1:177)
tree-gateway_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/tree-gateway/node_modules/swagger-client/dist/index.js:1:15877)
```

**Comment by thiagobustamante** [comment]
Hi, I saw this error only when using npm 5.6.0. It looks like this npm version has a bug when resolvin the dependencies tree. I just updated my npm to 6.1.1 and the error disappeared.

Please, try install the latest npm version: 

```sh
npm i -g npm
```
PS: I did not have this issue with npm versions prior to 5.6
